title: Introduction
author: Jo Mag
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  At 20 years old, I have no degree, so I decided to dedicate myself to coding.
  Follow my educational journey!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima 
